# Generated by Django 3.2 on 2022-11-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_rename_category_women_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='photo',
        ),
    ]
